//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B4F.TotalGiro.ApplicationLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.0.0.34/ReportServer/ReportExecution2005.asmx")]
        public string B4F_TotalGiro_ApplicationLayer_ReportExecutionEngine_ReportExecutionService {
            get {
                return ((string)(this["B4F_TotalGiro_ApplicationLayer_ReportExecutionEngine_ReportExecutionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserName=TFSSETUP; Password=Bits4321; Domain=BORGHOLS")]
        public string B4F_TotalGiro_ApplicationLayer_ReportExecutionEngine_ReportExecutionService_Credentials {
            get {
                return ((string)(this["B4F_TotalGiro_ApplicationLayer_ReportExecutionEngine_ReportExecutionService_Crede" +
                    "ntials"]));
            }
        }
    }
}
